FROM apache/superset:latest

USER root

# Install required packages
RUN apt-get update && \
    apt-get install -y python3-pip postgresql-client && \
    pip install psycopg2-binary kafka-python requests

USER superset