# Superset configuration
FEATURE_FLAGS = {
    "ENABLE_TEMPLATE_PROCESSING": True,
    "ALERT_REPORTS": True,
    "DASHBOARD_RBAC": True,
    "DASHBOARD_CROSS_FILTERS": True,
}

PUBLIC_ROLE_LIKE_GAMMA = True
SUPERSET_WEBSERVER_TIMEOUT = 300
ENABLE_PROXY_FIX = True
TALISMAN_ENABLED = False

# Map configuration
ENABLE_DECK_GL = True
DECK_GL_MAPBOX_API_KEY = ""

# Security
WTF_CSRF_ENABLED = True
WTF_CSRF_TIME_LIMIT = 3600